allowBuilds:
  '@depot/cli': false
  esbuild: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - "@trigger.dev/build@4.5.12"
  - "@trigger.dev/core@4.5.12"
  - "@trigger.dev/sdk@4.5.12"
  - "trigger.dev@4.5.12"
  - '@trigger.dev/schema-to-json@4.5.12'
