import type { SeasonalOpportunityCatalogEntry } from "./seasonal-intelligence-types";

export const SEASONAL_INTELLIGENCE_TIME_ZONE = "America/New_York";

export const SEASONAL_OPPORTUNITY_CATALOG: readonly SeasonalOpportunityCatalogEntry[] = [
  {
    key: "new-year",
    name: "New Year",
    kind: "fixed-holiday",
    recommendedBusinessFocus: ["brand-awareness", "facility-parties"],
    recommendedCampaignObjective: "Promote early-year party planning",
    recommendedPlacements: ["feed", "story"],
    preparationLeadDays: 21,
    finalCallDays: 3,
    memoryThemeTokens: ["new year"],
  },
  {
    key: "valentines-day",
    name: "Valentine's Day",
    kind: "fixed-holiday",
    recommendedBusinessFocus: ["facility-parties", "private-parties"],
    recommendedCampaignObjective: "Promote private party bookings",
    recommendedPlacements: ["feed", "story", "reel"],
    preparationLeadDays: 21,
    finalCallDays: 5,
    memoryThemeTokens: ["valentine"],
  },
  {
    key: "easter",
    name: "Easter",
    kind: "movable-holiday",
    recommendedBusinessFocus: ["outdoor-rentals", "bounce-houses", "church-events"],
    recommendedCampaignObjective: "Promote church/daycare/school events",
    recommendedPlacements: ["feed", "reel"],
    preparationLeadDays: 28,
    finalCallDays: 7,
    memoryThemeTokens: ["easter"],
  },
  {
    key: "spring-events",
    name: "Spring Events",
    kind: "season-window",
    recommendedBusinessFocus: ["outdoor-rentals", "bounce-houses", "school-daycare-events"],
    recommendedCampaignObjective: "Promote weekend inflatable rental openings",
    recommendedPlacements: ["feed", "reel"],
    preparationLeadDays: 21,
    finalCallDays: 14,
    memoryThemeTokens: ["spring"],
  },
  {
    key: "graduation-season",
    name: "Graduation Season",
    kind: "season-window",
    recommendedBusinessFocus: ["outdoor-rentals", "facility-parties", "private-parties"],
    recommendedCampaignObjective: "Promote birthday party bookings",
    recommendedPlacements: ["feed", "story"],
    preparationLeadDays: 21,
    finalCallDays: 10,
    memoryThemeTokens: ["graduation"],
  },
  {
    key: "memorial-day",
    name: "Memorial Day",
    kind: "movable-holiday",
    recommendedBusinessFocus: ["outdoor-rentals", "water-slides", "bounce-houses"],
    recommendedCampaignObjective: "Promote water slides for hot weather",
    recommendedPlacements: ["feed", "reel"],
    preparationLeadDays: 21,
    finalCallDays: 5,
    memoryThemeTokens: ["memorial day"],
  },
  {
    key: "summer",
    name: "Summer",
    kind: "season-window",
    recommendedBusinessFocus: ["water-slides", "outdoor-rentals", "bounce-houses"],
    recommendedCampaignObjective: "Promote water slides for hot weather",
    recommendedPlacements: ["feed", "reel", "story"],
    preparationLeadDays: 21,
    finalCallDays: 14,
    memoryThemeTokens: ["summer"],
  },
  {
    key: "fourth-of-july",
    name: "Fourth of July",
    kind: "fixed-holiday",
    recommendedBusinessFocus: ["outdoor-rentals", "water-slides", "bounce-houses"],
    recommendedCampaignObjective: "Promote clean and safe local family fun",
    recommendedPlacements: ["feed", "reel"],
    preparationLeadDays: 28,
    finalCallDays: 5,
    memoryThemeTokens: ["fourth of july", "july 4"],
  },
  {
    key: "back-to-school",
    name: "Back-to-School Season",
    kind: "season-window",
    recommendedBusinessFocus: ["school-daycare-events", "church-events", "bounce-houses"],
    recommendedCampaignObjective: "Promote church/daycare/school events",
    recommendedPlacements: ["feed", "carousel"],
    preparationLeadDays: 21,
    finalCallDays: 10,
    memoryThemeTokens: ["back to school", "school"],
  },
  {
    key: "labor-day",
    name: "Labor Day",
    kind: "movable-holiday",
    recommendedBusinessFocus: ["outdoor-rentals", "water-slides"],
    recommendedCampaignObjective: "Promote last-minute rental availability",
    recommendedPlacements: ["feed", "story"],
    preparationLeadDays: 21,
    finalCallDays: 5,
    memoryThemeTokens: ["labor day"],
  },
  {
    key: "fall-festivals",
    name: "Fall Festivals",
    kind: "season-window",
    recommendedBusinessFocus: ["outdoor-rentals", "church-events", "school-daycare-events"],
    recommendedCampaignObjective: "Promote church/daycare/school events",
    recommendedPlacements: ["feed", "reel"],
    preparationLeadDays: 21,
    finalCallDays: 14,
    memoryThemeTokens: ["fall", "festival"],
  },
  {
    key: "halloween",
    name: "Halloween",
    kind: "fixed-holiday",
    recommendedBusinessFocus: ["outdoor-rentals", "bounce-houses", "facility-parties"],
    recommendedCampaignObjective: "Promote birthday party bookings",
    recommendedPlacements: ["feed", "reel", "story"],
    preparationLeadDays: 28,
    finalCallDays: 7,
    memoryThemeTokens: ["halloween"],
  },
  {
    key: "thanksgiving",
    name: "Thanksgiving",
    kind: "movable-holiday",
    recommendedBusinessFocus: ["facility-parties", "private-parties", "brand-awareness"],
    recommendedCampaignObjective: "Promote private party bookings",
    recommendedPlacements: ["feed"],
    preparationLeadDays: 21,
    finalCallDays: 5,
    memoryThemeTokens: ["thanksgiving"],
  },
  {
    key: "christmas",
    name: "Christmas",
    kind: "fixed-holiday",
    recommendedBusinessFocus: ["facility-parties", "private-parties", "brand-awareness"],
    recommendedCampaignObjective: "Promote indoor facility parties",
    recommendedPlacements: ["feed", "story", "carousel"],
    preparationLeadDays: 35,
    finalCallDays: 7,
    memoryThemeTokens: ["christmas"],
  },
  {
    key: "year-end-parties",
    name: "Year-End Holiday Parties",
    kind: "season-window",
    recommendedBusinessFocus: ["facility-parties", "private-parties"],
    recommendedCampaignObjective: "Promote private party bookings",
    recommendedPlacements: ["feed", "story"],
    preparationLeadDays: 28,
    finalCallDays: 10,
    memoryThemeTokens: ["holiday", "christmas", "new year"],
  },
] as const;
