import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migrationUrl=new URL("../../../supabase/migrations/20260820120000_create_agent_manager.sql",import.meta.url);
test("migration has atomic dedupe, skip-locked claim, bounded retries, RLS and emergency stop",async()=>{const sql=await readFile(migrationUrl,"utf8");assert.match(sql,/unique \(agent_id, idempotency_key\)/i);assert.match(sql,/for update of j skip locked/i);assert.match(sql,/attempt_count>=max_attempts/i);assert.match(sql,/emergency_stop/i);assert.equal((sql.match(/enable row level security/gi)||[]).length,5);assert.doesNotMatch(sql,/revoke all on all tables/i);});
test("wake route requires a secret and admin mutations require owner auth",async()=>{const wake=await readFile(new URL("../../app/api/agents/wake/route.ts",import.meta.url),"utf8");const control=await readFile(new URL("../../app/api/admin/agents/control/route.ts",import.meta.url),"utf8");assert.match(wake,/AGENT_MANAGER_WAKE_SECRET/);assert.match(wake,/authorization/);assert.match(control,/verifyAdminOwnerAccess/);assert.match(control,/validateOwnerPost/);});
test("safe manual job replay returns the durable terminal job without running it again",async()=>{const route=await readFile(new URL("../../app/api/admin/agents/jobs/route.ts",import.meta.url),"utf8");assert.match(route,/job\.status==="queued"\?await runOne/);assert.match(route,/deduplicated:job\.status!=="queued"/);});
test("Booking Agent triage is owner-only, request-guarded and read-only over booking workflow state",async()=>{const route=await readFile(new URL("../../app/api/admin/agents/booking-triage/route.ts",import.meta.url),"utf8");const service=await readFile(new URL("booking-triage-service.ts",import.meta.url),"utf8");assert.match(route,/verifyAdminOwnerAccess/);assert.match(route,/validateOwnerPost/);assert.match(service,/booking_integration_workflows/);assert.doesNotMatch(service,/\.update\(|\.delete\(|recordWorkflowOutcome|sendBookingOperationalAlert|openai|anthropic|model\.generate/i);});
test("Booking Agent client sends the JSON request required by the owner request guard",async()=>{const client=await readFile(new URL("../../app/admin/agents/BookingTriageClient.tsx",import.meta.url),"utf8");assert.match(client,/"Content-Type":\s*"application\/json"/);assert.match(client,/body:\s*"\{\}"/);});
test("approval boundaries include every high-impact category",async()=>{const source=await readFile(new URL("service.ts",import.meta.url),"utf8");for(const action of ["production.deploy","database.destructive","schema.production","credentials.change","provider.paid_enable","billing.change","message.bulk","git.destructive","git.merge_protected"])assert.match(source,new RegExp(action.replace(".","\\.")));});
test("Trigger.dev proof is deterministic, bounded, idempotent and owner-only",async()=>{const task=await readFile(new URL("../../trigger/agent-manager-proof.ts",import.meta.url),"utf8");const route=await readFile(new URL("../../app/api/admin/agents/trigger-proof/route.ts",import.meta.url),"utf8");const bridge=await readFile(new URL("trigger-proof.ts",import.meta.url),"utf8");assert.match(task,/maxAttempts:\s*3/);assert.match(task,/ctx\.attempt\.number === 1/);assert.match(task,/aiInvocations:\s*0/);assert.doesNotMatch(task,/openai|anthropic|model\.generate/i);assert.match(bridge,/idempotencyKeyTTL/);assert.match(route,/verifyAdminOwnerAccess/);assert.match(route,/httpOnly:\s*true/);});
test("Nomination Agent is deterministic, idempotent, owner-started and fixture-safe",async()=>{const task=await readFile(new URL("../../trigger/nomination-agent.ts",import.meta.url),"utf8");const route=await readFile(new URL("../../app/api/admin/agents/nomination-proof/route.ts",import.meta.url),"utf8");const callback=await readFile(new URL("../../app/api/admin/agents/nomination-proof/callback/route.ts",import.meta.url),"utf8");const bridge=await readFile(new URL("nomination-trigger.ts",import.meta.url),"utf8");assert.match(task,/maxAttempts:\s*3/);assert.match(task,/parseNominationEmail/);assert.match(task,/aiInvocations:\s*0/);assert.doesNotMatch(task,/openai|anthropic|model\.generate/i);assert.match(bridge,/idempotencyKeyTTL/);assert.match(route,/verifyAdminOwnerAccess/);assert.match(route,/validateOwnerPost/);assert.match(route,/isLocalAgentPreviewEnabled/);assert.match(callback,/isLocalAgentPreviewEnabled/);assert.match(callback,/saveGiveawayNomination\(nomination, "fixture"\)/);});
test("production nomination inbound is signed, disabled by default, durable and status-recorded",async()=>{const webhook=await readFile(new URL("../../app/api/agents/nomination/resend-webhook/route.ts",import.meta.url),"utf8");const callback=await readFile(new URL("../../app/api/agents/nomination/callback/route.ts",import.meta.url),"utf8");const task=await readFile(new URL("../../trigger/nomination-agent.ts",import.meta.url),"utf8");assert.match(webhook,/NOMINATION_AGENT_INBOUND_ENABLED/);assert.match(webhook,/request\.text\(\)/);assert.match(webhook,/webhooks\.verify/);assert.match(webhook,/assertAgentDispatchAllowed/);assert.match(webhook,/enqueueJob/);assert.match(webhook,/triggerNominationInbound/);assert.match(callback,/hasAgentCallbackAuthorization/);assert.match(callback,/saveGiveawayNomination\(nomination, "production"\)/);assert.match(callback,/recordNominationJobResult/);assert.match(task,/AGENT_MANAGER_CALLBACK_SECRET/);assert.match(task,/callback\.protocol !== "https:"/);assert.doesNotMatch(webhook+callback+task,/openai|anthropic|model\.generate/i);});
