begin;
-- Publish a new immutable legal version; historical versions are retained.
do $publish$
declare t uuid; v uuid; n integer;
begin
  select id into t from public.waiver_templates where slug='jumping-jax-llc-waiver-of-liability' and status='active' for update;
  if t is null then raise exception 'Active Jumping Jax waiver template not found'; end if;
  select coalesce(max(version_number),0)+1 into n from public.waiver_template_versions where template_id=t;
  insert into public.waiver_template_versions(template_id,version_number,body_html,body_sha256,published_by_staff_id)
  values(t,n,$terms$<h1>Jumping Jax LLC — Participant Agreement, Assumption of Risk and Release</h1>
<p><strong>READ BEFORE SIGNING. THIS AGREEMENT AFFECTS LEGAL RIGHTS, INCLUDING CERTAIN RIGHTS TO BRING CLAIMS.</strong></p>
<p>This agreement is made on {{WAIVER_CURRENT_DATE}} in consideration of admission to and participation at Jumping Jax LLC’s indoor facility in Greenwood, South Carolina. “Jumping Jax” means Jumping Jax LLC. “Released Parties” means Jumping Jax LLC and its members, owners, managers, employees, instructors and agents acting in connection with the facility and activities covered by this agreement.</p>
<h2>Activities and risks</h2>
<p>The covered activities include indoor Open Play, birthday parties, bouncing, jumping, climbing, sliding, games, use of inflatable and other play equipment, supervision or observation of those activities, and access to the associated indoor facility and common areas. This facility agreement does not replace a separate off-site rental agreement.</p>
<p>These activities involve risks including falls; collisions with other people, equipment or surfaces; differences in participants’ ages, sizes and abilities; equipment failure or improper use; slips, trips and falls; physical exertion; and acts or omissions of other guests. Injury may include scrapes, bruises, cuts, sprains, broken bones, head or spinal injuries, paralysis or death. Some risks cannot be eliminated without changing the nature of the activities.</p>
<h2>Safety responsibilities and voluntary participation</h2>
<p>I voluntarily choose to participate and, for each child for whom I sign as parent or legal guardian, authorize that child’s participation. I understand the risks described above and knowingly assume the risks of participation to the extent permitted by law. I will follow posted rules and staff instructions, use equipment only as directed and within posted age, size and occupancy limits, supervise my children as required, and promptly tell staff about hazards or injuries. I will not participate while impaired or contrary to applicable health restrictions. I understand that unsafe behavior can result in removal from play.</p>
<h2>Limited release of claims</h2>
<p><strong>TO THE EXTENT PERMITTED BY SOUTH CAROLINA LAW, I RELEASE THE RELEASED PARTIES FROM CLAIMS FOR PERSONAL INJURY, DEATH OR PROPERTY DAMAGE ARISING FROM THE COVERED ACTIVITIES OR USE OF THE COVERED FACILITY, INCLUDING CLAIMS ARISING FROM A RELEASED PARTY’S ORDINARY NEGLIGENCE.</strong> This includes ordinary-negligence claims involving operation, instruction, supervision, maintenance or the condition of covered equipment or premises. This release applies to my own claims and, only to the extent I have lawful authority to do so, claims relating to each child identified under my agreement.</p>
<p><strong>This agreement does not release gross negligence, recklessness, willful or wanton misconduct, intentional misconduct, or liability that cannot lawfully be released.</strong> It does not represent that all claims of a child can be waived. Nothing here excuses compliance with applicable safety duties or requires the waiver of a right that applicable law makes nonwaivable.</p>
<h2>Adults and children</h2>
<p>Every adult listed must personally complete their own agreement and electronic signature. Every child must be identified by name and date of birth and linked to their actual parent or legal guardian. A friend, relative, party host or other accompanying adult is not accepted as a child’s signing guardian merely because that adult brought the child or has informal permission. The signing parent or guardian confirms their legal authority for the children specifically identified under their signature. A parent or guardian who is watching must still sign for their children.</p>
<h2>Duration and return visits</h2>
<p>This agreement applies to the signing visit and subsequent covered visits until the displayed expiration date, which is the three-year anniversary of signing. It expires at the start of that date in the America/New_York time zone. A person covered as a child must complete their own adult agreement before participating at age 18. Jumping Jax may require a new agreement when material terms, activities or circumstances change. Each visit and the people actually attending are recorded separately from this signed group agreement.</p>
<h2>Admission</h2>
<p>Watching adults are free. Playing adults are $10. Children age 2 and under are $7; children age 3 and older are $10. Age and admission are determined on the visit date. An adult who changes from watching to playing owes playing-adult admission. At staff checkout, an accepted free pass covers the admission of its specifically assigned participant. Cash or card may cover the remaining balance. A free pass does not replace a completed waiver.</p>
<h2>Electronic agreement and copies</h2>
<p>Each signing adult must type their own first and last name, matching that adult’s name on this waiver, and separately confirm the required acknowledgments. By doing so, that adult agrees to transact and sign electronically and intends the entered name to be their electronic signature. Signing for one adult does not sign for other adults. The completed record retains the waiver version, covered people, guardian links, typed signatures, acknowledgments and signing time. A completed copy can be printed or downloaded. Anyone who cannot or does not wish to sign electronically should contact staff before participating to arrange an alternative.</p>
<h2>Optional photographs</h2>
<p>Permission for promotional use of photographs of an adult and their identified children is optional and is recorded separately for each signing adult. Declining that permission does not prevent completion of this waiver or admission. Photograph permission must be respected according to each person’s recorded choice.</p>
<h2>Applicable law and remaining terms</h2>
<p>South Carolina law governs this agreement subject to applicable mandatory law. If a provision is unenforceable, the remaining provisions remain effective to the extent permitted by law. This agreement does not include an arbitration requirement or a promise that no lawsuit can be brought. By completing my individual agreement, I confirm that I have had an opportunity to read the terms, ask staff questions, and understand the agreement before voluntarily signing.</p>$terms$,encode(sha256(convert_to($terms$<h1>Jumping Jax LLC — Participant Agreement, Assumption of Risk and Release</h1>
<p><strong>READ BEFORE SIGNING. THIS AGREEMENT AFFECTS LEGAL RIGHTS, INCLUDING CERTAIN RIGHTS TO BRING CLAIMS.</strong></p>
<p>This agreement is made on {{WAIVER_CURRENT_DATE}} in consideration of admission to and participation at Jumping Jax LLC’s indoor facility in Greenwood, South Carolina. “Jumping Jax” means Jumping Jax LLC. “Released Parties” means Jumping Jax LLC and its members, owners, managers, employees, instructors and agents acting in connection with the facility and activities covered by this agreement.</p>
<h2>Activities and risks</h2>
<p>The covered activities include indoor Open Play, birthday parties, bouncing, jumping, climbing, sliding, games, use of inflatable and other play equipment, supervision or observation of those activities, and access to the associated indoor facility and common areas. This facility agreement does not replace a separate off-site rental agreement.</p>
<p>These activities involve risks including falls; collisions with other people, equipment or surfaces; differences in participants’ ages, sizes and abilities; equipment failure or improper use; slips, trips and falls; physical exertion; and acts or omissions of other guests. Injury may include scrapes, bruises, cuts, sprains, broken bones, head or spinal injuries, paralysis or death. Some risks cannot be eliminated without changing the nature of the activities.</p>
<h2>Safety responsibilities and voluntary participation</h2>
<p>I voluntarily choose to participate and, for each child for whom I sign as parent or legal guardian, authorize that child’s participation. I understand the risks described above and knowingly assume the risks of participation to the extent permitted by law. I will follow posted rules and staff instructions, use equipment only as directed and within posted age, size and occupancy limits, supervise my children as required, and promptly tell staff about hazards or injuries. I will not participate while impaired or contrary to applicable health restrictions. I understand that unsafe behavior can result in removal from play.</p>
<h2>Limited release of claims</h2>
<p><strong>TO THE EXTENT PERMITTED BY SOUTH CAROLINA LAW, I RELEASE THE RELEASED PARTIES FROM CLAIMS FOR PERSONAL INJURY, DEATH OR PROPERTY DAMAGE ARISING FROM THE COVERED ACTIVITIES OR USE OF THE COVERED FACILITY, INCLUDING CLAIMS ARISING FROM A RELEASED PARTY’S ORDINARY NEGLIGENCE.</strong> This includes ordinary-negligence claims involving operation, instruction, supervision, maintenance or the condition of covered equipment or premises. This release applies to my own claims and, only to the extent I have lawful authority to do so, claims relating to each child identified under my agreement.</p>
<p><strong>This agreement does not release gross negligence, recklessness, willful or wanton misconduct, intentional misconduct, or liability that cannot lawfully be released.</strong> It does not represent that all claims of a child can be waived. Nothing here excuses compliance with applicable safety duties or requires the waiver of a right that applicable law makes nonwaivable.</p>
<h2>Adults and children</h2>
<p>Every adult listed must personally complete their own agreement and electronic signature. Every child must be identified by name and date of birth and linked to their actual parent or legal guardian. A friend, relative, party host or other accompanying adult is not accepted as a child’s signing guardian merely because that adult brought the child or has informal permission. The signing parent or guardian confirms their legal authority for the children specifically identified under their signature. A parent or guardian who is watching must still sign for their children.</p>
<h2>Duration and return visits</h2>
<p>This agreement applies to the signing visit and subsequent covered visits until the displayed expiration date, which is the three-year anniversary of signing. It expires at the start of that date in the America/New_York time zone. A person covered as a child must complete their own adult agreement before participating at age 18. Jumping Jax may require a new agreement when material terms, activities or circumstances change. Each visit and the people actually attending are recorded separately from this signed group agreement.</p>
<h2>Admission</h2>
<p>Watching adults are free. Playing adults are $10. Children age 2 and under are $7; children age 3 and older are $10. Age and admission are determined on the visit date. An adult who changes from watching to playing owes playing-adult admission. At staff checkout, an accepted free pass covers the admission of its specifically assigned participant. Cash or card may cover the remaining balance. A free pass does not replace a completed waiver.</p>
<h2>Electronic agreement and copies</h2>
<p>Each signing adult must type their own first and last name, matching that adult’s name on this waiver, and separately confirm the required acknowledgments. By doing so, that adult agrees to transact and sign electronically and intends the entered name to be their electronic signature. Signing for one adult does not sign for other adults. The completed record retains the waiver version, covered people, guardian links, typed signatures, acknowledgments and signing time. A completed copy can be printed or downloaded. Anyone who cannot or does not wish to sign electronically should contact staff before participating to arrange an alternative.</p>
<h2>Optional photographs</h2>
<p>Permission for promotional use of photographs of an adult and their identified children is optional and is recorded separately for each signing adult. Declining that permission does not prevent completion of this waiver or admission. Photograph permission must be respected according to each person’s recorded choice.</p>
<h2>Applicable law and remaining terms</h2>
<p>South Carolina law governs this agreement subject to applicable mandatory law. If a provision is unenforceable, the remaining provisions remain effective to the extent permitted by law. This agreement does not include an arbitration requirement or a promise that no lawsuit can be brought. By completing my individual agreement, I confirm that I have had an opportunity to read the terms, ask staff questions, and understand the agreement before voluntarily signing.</p>$terms$,'UTF8')),'hex'),'waiver-group-upgrade') returning id into v;
  update public.waiver_templates set current_version_id=v,required_version_id=v,updated_at=now() where id=t;
end;
$publish$;
notify pgrst, 'reload schema';
commit;
