/**
 * AUTO-GENERATED by scripts/generate-public-asset-metadata.mjs.
 * Every image currently shipped from public/ is measured with Sharp.
 */
export type PublicAssetMetadata = Readonly<{
  width: number;
  height: number;
  format: string;
}>;

export const PUBLIC_ASSET_METADATA: Readonly<Record<string, PublicAssetMetadata>> = {
  "/hero.jpg": {
    "width": 1080,
    "height": 1351,
    "format": "jpeg"
  },
  "/inflatables/accessories/40in-helium-number-balloons.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/accessories/6-ft-table.jpg": {
    "width": 1000,
    "height": 1000,
    "format": "jpeg"
  },
  "/inflatables/accessories/8-ft-table.jpg": {
    "width": 1000,
    "height": 1000,
    "format": "jpeg"
  },
  "/inflatables/accessories/chairs.jpg": {
    "width": 474,
    "height": 645,
    "format": "jpeg"
  },
  "/inflatables/accessories/cotton-candy-birthday-package.jpg": {
    "width": 608,
    "height": 608,
    "format": "jpeg"
  },
  "/inflatables/accessories/cotton-candy.jpg": {
    "width": 608,
    "height": 608,
    "format": "jpeg"
  },
  "/inflatables/accessories/dunk-tank.jpg": {
    "width": 290,
    "height": 198,
    "format": "jpeg"
  },
  "/inflatables/accessories/generator.jpg": {
    "width": 202,
    "height": 202,
    "format": "jpeg"
  },
  "/inflatables/accessories/helium-latex-balloons.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/accessories/inflatable-birthday-chair.jpg": {
    "width": 810,
    "height": 1080,
    "format": "jpeg"
  },
  "/inflatables/accessories/popcorn-machine.jpg": {
    "width": 612,
    "height": 612,
    "format": "jpeg"
  },
  "/inflatables/accessories/sno-cone.jpg": {
    "width": 600,
    "height": 600,
    "format": "jpeg"
  },
  "/inflatables/bounce-houses/castle.webp": {
    "width": 261,
    "height": 260,
    "format": "webp"
  },
  "/inflatables/bounce-houses/dalmation-bounce.webp": {
    "width": 600,
    "height": 600,
    "format": "webp"
  },
  "/inflatables/bounce-houses/dream-castle.webp": {
    "width": 313,
    "height": 273,
    "format": "webp"
  },
  "/inflatables/bounce-houses/jumbo-castle-bouncer.webp": {
    "width": 600,
    "height": 576,
    "format": "webp"
  },
  "/inflatables/bounce-houses/tiger-belly-bounce.jpg": {
    "width": 900,
    "height": 787,
    "format": "jpeg"
  },
  "/inflatables/combos/candy-land-toddle-combo.jpg": {
    "width": 600,
    "height": 351,
    "format": "jpeg"
  },
  "/inflatables/combos/cars-combo.webp": {
    "width": 230,
    "height": 171,
    "format": "webp"
  },
  "/inflatables/combos/castle-combo.webp": {
    "width": 600,
    "height": 464,
    "format": "webp"
  },
  "/inflatables/combos/combo1.jpg": {
    "width": 390,
    "height": 346,
    "format": "jpeg"
  },
  "/inflatables/combos/dream-combo.webp": {
    "width": 268,
    "height": 239,
    "format": "webp"
  },
  "/inflatables/combos/fairies-combo.webp": {
    "width": 210,
    "height": 175,
    "format": "webp"
  },
  "/inflatables/combos/island-breeze-combo.webp": {
    "width": 600,
    "height": 800,
    "format": "webp"
  },
  "/inflatables/combos/spongebob-combo.webp": {
    "width": 225,
    "height": 149,
    "format": "webp"
  },
  "/inflatables/combos/whoville-igloo-combo-grinch-themed-inflatable-bounce-house.webp": {
    "width": 600,
    "height": 400,
    "format": "webp"
  },
  "/inflatables/combos/world-of-disney.webp": {
    "width": 221,
    "height": 184,
    "format": "webp"
  },
  "/inflatables/foam-parties/foam-parties.jpg": {
    "width": 2100,
    "height": 2100,
    "format": "jpeg"
  },
  "/inflatables/inflatable-games/4-in-1-sports-game.webp": {
    "width": 600,
    "height": 585,
    "format": "webp"
  },
  "/inflatables/inflatable-games/floating-baseball-game.jpg": {
    "width": 259,
    "height": 198,
    "format": "jpeg"
  },
  "/inflatables/inflatable-games/football-game.jpg": {
    "width": 600,
    "height": 800,
    "format": "jpeg"
  },
  "/inflatables/inflatable-games/human-whackamole.webp": {
    "width": 600,
    "height": 574,
    "format": "webp"
  },
  "/inflatables/inflatable-games/hungry-hippo.jpg": {
    "width": 224,
    "height": 198,
    "format": "jpeg"
  },
  "/inflatables/inflatable-games/jumpingjax-basketball-shootout.webp": {
    "width": 600,
    "height": 416,
    "format": "webp"
  },
  "/inflatables/inflatable-games/sports-star.webp": {
    "width": 248,
    "height": 198,
    "format": "webp"
  },
  "/inflatables/obstacle-courses/call-of-duty-course.webp": {
    "width": 400,
    "height": 166,
    "format": "webp"
  },
  "/inflatables/obstacle-courses/criss-cross-course.jpg": {
    "width": 560,
    "height": 560,
    "format": "jpeg"
  },
  "/inflatables/obstacle-courses/grinch-whoville-mayhem.webp": {
    "width": 600,
    "height": 400,
    "format": "webp"
  },
  "/inflatables/obstacle-courses/offshore-obstacle-course.webp": {
    "width": 300,
    "height": 300,
    "format": "webp"
  },
  "/inflatables/obstacle-courses/sports-course.webp": {
    "width": 400,
    "height": 206,
    "format": "webp"
  },
  "/inflatables/obstacle-courses/toxic-course.webp": {
    "width": 400,
    "height": 233,
    "format": "webp"
  },
  "/inflatables/slides/18-ft-slide.webp": {
    "width": 241,
    "height": 195,
    "format": "webp"
  },
  "/inflatables/slides/18-ft-tropical-double-lane-slide.webp": {
    "width": 600,
    "height": 649,
    "format": "webp"
  },
  "/inflatables/slides/24-ft-slide.webp": {
    "width": 400,
    "height": 521,
    "format": "webp"
  },
  "/inflatables/slides/30-ft-long-rock-climb-slide.webp": {
    "width": 600,
    "height": 600,
    "format": "webp"
  },
  "/inflatables/slides/pirate-slide.webp": {
    "width": 400,
    "height": 283,
    "format": "webp"
  },
  "/inflatables/slides/princess-slide.webp": {
    "width": 394,
    "height": 296,
    "format": "webp"
  },
  "/inflatables/slides/sugar-rush-slide.webp": {
    "width": 600,
    "height": 464,
    "format": "webp"
  },
  "/inflatables/waterslides/18-ft-tropical-double-lane-waterslide.webp": {
    "width": 600,
    "height": 649,
    "format": "webp"
  },
  "/inflatables/waterslides/island-breeze-combo-waterslide.webp": {
    "width": 600,
    "height": 800,
    "format": "webp"
  },
  "/inflatables/waterslides/legacy/18-ft-basic-waterslide.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/22-ft-hurricane-waterslide.jpg": {
    "width": 222,
    "height": 198,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/22-ft-tropical-hurricane-waterslide.jpg": {
    "width": 957,
    "height": 696,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/double-lane-18ft-waterslide.jpg": {
    "width": 232,
    "height": 198,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/double-splash-waterslide.jpg": {
    "width": 284,
    "height": 213,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/mini-tiki-plunge.jpg": {
    "width": 530,
    "height": 366,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/mini-waterslide-2.jpg": {
    "width": 1284,
    "height": 1562,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/mini-waterslide.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/purple-hurricane-18ft.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/rampage-doublelane-waterslide.jpg": {
    "width": 477,
    "height": 339,
    "format": "jpeg"
  },
  "/inflatables/waterslides/legacy/ruby-falls-waterslide-with-deep-pool.jpg": {
    "width": 3024,
    "height": 4032,
    "format": "jpeg"
  },
  "/inflatables/waterslides/pirate-waterslide.webp": {
    "width": 400,
    "height": 283,
    "format": "webp"
  },
  "/inflatables/waterslides/princess-waterslide.webp": {
    "width": 394,
    "height": 296,
    "format": "webp"
  },
  "/inflatables/yard-games/basketball-game.webp": {
    "width": 213,
    "height": 213,
    "format": "webp"
  },
  "/inflatables/yard-games/dunk-tank.webp": {
    "width": 290,
    "height": 198,
    "format": "webp"
  },
  "/invitation-library/shared/balloon.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/confetti.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/gift.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/palm.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/rainbow.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/sparkles.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/shared/star.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/classic-birthday/cake.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/classic-birthday/party-popper.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/classic-birthday/tile-heart.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/construction/cone.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/construction/lorry.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/construction/pickup.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/construction/tile-brick.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/construction/tractor.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/construction/worker.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/dinosaur/dragon.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/dinosaur/lizard.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/dinosaur/sauropod.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/dinosaur/tile-grass.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/dinosaur/trex.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/controller.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/gem.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/joystick.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/monster.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/puzzle.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/gamer-neon/tile-pixel.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/anchor.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/fish.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/octopus.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/sailboat.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/tile-water.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/ocean-mermaid/whale.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/pirate/compass.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/pirate/flag.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/pirate/parrot.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/pirate/skull.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/pirate/tile-wood.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/castle.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/crown.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/fairy.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/gem.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/princess.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/princess-royal/tile-gem.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/racing-cars/car.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/racing-cars/flag.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/racing-cars/racer.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/racing-cars/tile-track.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/racing-cars/trophy.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/dog.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/elephant.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/giraffe.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/guide-dog.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/lion.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/tiger.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/safari-animals/tile-bush.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/space/alien.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/space/moon.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/space/planet.png": {
    "width": 256,
    "height": 264,
    "format": "png"
  },
  "/invitation-library/themes/space/rocket.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/space/shooting-star.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/space/tile-block.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/sports/baseball.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/sports/basketball.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/sports/football.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/sports/soccer.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/sports/tile-flag.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/sports/trophy.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/unicorn-rainbow/crystal.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitation-library/themes/unicorn-rainbow/tile-star.png": {
    "width": 18,
    "height": 18,
    "format": "png"
  },
  "/invitation-library/themes/unicorn-rainbow/unicorn.png": {
    "width": 256,
    "height": 256,
    "format": "png"
  },
  "/invitations/approved/block-world/card.png": {
    "width": 1536,
    "height": 1024,
    "format": "png"
  },
  "/invitations/approved/sonic/card.png": {
    "width": 1536,
    "height": 1024,
    "format": "png"
  },
  "/logo.png": {
    "width": 3010,
    "height": 1612,
    "format": "png"
  },
  "/marketing/free-party-giveaway-background.png": {
    "width": 1103,
    "height": 1426,
    "format": "png"
  },
  "/marketing/free-party-giveaway-flyer-v2.png": {
    "width": 1700,
    "height": 2200,
    "format": "png"
  },
  "/marketing/free-party-giveaway-flyer-v3.png": {
    "width": 1700,
    "height": 2200,
    "format": "png"
  },
  "/marketing/free-party-giveaway-flyer.png": {
    "width": 1700,
    "height": 2200,
    "format": "png"
  },
  "/marketing/jumping-jax-facility-empty-v2.png": {
    "width": 1448,
    "height": 1086,
    "format": "png"
  },
  "/marketing/meta/giveaway-feed-1080x1350.png": {
    "width": 1080,
    "height": 1350,
    "format": "png"
  },
  "/marketing/meta/giveaway-story-1080x1920.png": {
    "width": 1080,
    "height": 1920,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-castle-v1.png": {
    "width": 1254,
    "height": 1254,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-feed-01.png": {
    "width": 1080,
    "height": 1350,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-feed-02.png": {
    "width": 1080,
    "height": 1350,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-reel-01.png": {
    "width": 1080,
    "height": 1920,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-reel-02.png": {
    "width": 1080,
    "height": 1920,
    "format": "png"
  },
  "/marketing/meta/weekend-10-off-waterslide-v1.png": {
    "width": 1254,
    "height": 1254,
    "format": "png"
  }
} as const;
